### ISSUE TITLE
Update Orpheus Invite Forum Requirements

### ISSUE THREAD

**Issue by KNIF** [PredictablePirate/TrackerInviteThreads#1]
As you can see in the following image, Orpheus (OPS) now has different requirements for their invite forum now requiring the `Elite` instead of the `Power User` rank in order to be able to see the invite forum.

![Orpheus Classes](https://i.imgur.com/H1UfQ5V.png)
(Screenshot taken on Feb 08, 2021)

**Comment by PredictablePirate** [comment]
Thanks so much :) I've updated it with the new information

https://github.com/PredictablePirate/TrackerInviteThreads/commit/0c8b8e14941a76b504610c0e0db1d3ce97a40b6b
